# Generated by Django 6.0.7 on 2026-07-24 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organizations.organization')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_service_per_organization')],
            },
        ),
    ]
