# Generated by Django 6.0.7 on 2026-07-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('services', '0001_initial'),
        ('teams', '0002_alter_team_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='service',
            name='unique_service_per_organization',
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_service_name_per_org'),
        ),
    ]
